import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>Test Site 2</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/test2',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/test2',
  footer: {
    text: 'Test Site 2 - Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – Test Site 2'
    }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="Test Site 2" />
      <meta property="og:description" content="Documentation for Test Site 2" />
    </>
  )
}

export default config
